Logging polish (part 2)
decline-cookies/anvil-csharp-core pull request #115
Opened 2022-10-06 22:29 UTC by tjvezina

1. Omit line number from log context when zero
2. Corrected outdated documentation comment

### What is the current behaviour?
Logs from managed code have line number zero in the context, ex: `(UnityLogListener:0|.ctor) message`

### What is the new behaviour?
Logs from managed code now omit the line number, ex: `(UnityLogListener|.ctor) message`

Note: The same functionality does not apply to `FileLogHandler` as it allows the user to define a log context format string, making it confusing if part of that format is silently omitted in some cases. It would be nearly impossible to cleanly omit the line number in custom format strings anyway.

### What PRs does this depend on?
 - None

### Does this introduce a breaking change?
 - [ ] Yes 
 - [X] No

2022-10-07 01:36 UTC, jkeon submitted a review, later dismissed
Looks good. 

Why would the line number be 0 ever though? Maybe I'm not fully understanding the case when it is 0?

2022-10-07 11:57 UTC, tjvezina commented
It's just the default value returned by `StackFrame.GetFileLineNumber()` - so if the log context fails to resolve you'd see `(unknown|unknown)`, or more likely if the log comes from a DLL or other managed code, there is no file/line to point to, so we fall back on showing `DeclaringType.Name` and omit the line number, ex `(UnityLogListener|.ctor)`.

2022-10-07 15:50 UTC, mbaker3 requested changes
> Note: The same functionality does not apply to FileLogHandler as it allows the user to define a log context format string, making it confusing if part of that format is silently omitted in some cases. It would be nearly impossible to cleanly omit the line number in custom format strings anyway.

Yea that's a shame because it's the direction all of the handlers will move eventually.
When we do take on that effort maybe we just include two different versions of the caller line token.
`LOG_CONTEXT_CALLER_LINE_ALWAYS` and `LOG_CONTEXT_CALLER_LINE` where one would only show conditionally, maybe with one way to associate the separator with the conditional version so they could both be omitted effectively when unknown.

I suppose the other option is just to replace line number with `?` or `NaN` or something when it's not known.

2022-10-07 15:50 UTC, mbaker3 commented on Logging/.CSProject/LogHandler/ConsoleLogHandler.cs
> +            message = $"({context}) {message}";
Same as comment here. Remove extra string allocation
https://github.com/decline-cookies/anvil-unity-core/pull/82#discussion_r990223627

2022-10-07 17:46 UTC, mbaker3 submitted a review, later dismissed

2022-10-07 17:47 UTC, mbaker3 commented on Logging/.CSProject/LogHandler/ConsoleLogHandler.cs
> +            }
```suggestion
            if (callerLine > 0)
            {
               message = $"({callerFile}:{callerLine}|{callerName}) {message}";
            }
            else
            {
               message = $"({callerFile}|{callerName}) {message}";
            }
```

2022-10-07 17:48 UTC, mbaker3 approved these changes

2022-10-07 17:48 UTC, merged

2022-10-11 07:04 UTC, jkeon commented
Ahh gotcha. Ok cool thanks

On Fri, Oct 7, 2022 at 7:57 AM Tyler Vezina ***@***.***>
wrote:

> It's just the default value returned by StackFrame.GetFileLineNumber() -
> so if the log context fails to resolve you'd see (unknown|unknown), or
> more likely if the log comes from a DLL or other managed code, there is no
> file/line to point to, so we fall back on showing DeclaringType.Name and
> omit the line number, ex (UnityLogListener|.ctor).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/decline-cookies/anvil-csharp-core/pull/115#issuecomment-1271497505>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACSYQH5THV4LIMGYA774HTWCAF2HANCNFSM6AAAAAAQ7B6RIA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>